[project]
name = "ren-vault"
description = "A Clarity 4-powered micro-savings vault protocol"
authors = ["RenVault Team"]
telemetry = false
cache_dir = "./.clarinet"

[contracts.ren-vault]
path = "contracts/ren-vault.clar"
clarity_version = 2
epoch = 2.4

[contracts.multi-asset-vault]
path = "contracts/multi-asset-vault.clar"
clarity_version = 2
epoch = 2.4

[contracts.asset-manager]
path = "contracts/asset-manager.clar"
clarity_version = 2
epoch = 2.4
depends_on = ["sip010-trait"]

[contracts.sip010-trait]
path = "contracts/traits/sip010-trait.clar"
clarity_version = 2
epoch = 2.4

[contracts.vault-trait]
path = "contracts/traits/vault-trait.clar"
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false