[project]
name = "ren-vault"
description = "A Clarity 4 micro-savings vault with commitment points and protocol fees"
authors = ["RenVault Team"]
telemetry = false
cache_dir = "./.cache"
requirements = []
boot_contracts = []

[contracts.ren-vault]
path = "contracts/ren-vault.clar"
clarity_version = 2
epoch = "2.4"

[contracts.vault-trait]
path = "contracts/traits/vault-trait.clar"
clarity_version = 2
epoch = "2.4"

[repl]
costs_version = 2
parser_version = 2