[network]
name = "testnet"
stacks_node_rpc_address = "https://stacks-node-api.testnet.stacks.co"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "YOUR_TESTNET_MNEMONIC_HERE"
balance = 100_000_000_000_000